### ISSUE TITLE
sshfs not working

### ISSUE THREAD

**Issue by schmonz** [vmactions/netbsd-vm#5]
Hi! These Actions are extremely handy for anyone actually interested in platform portability. Thank you for providing them.

I wanted to compare `sync: sshfs` with `sync: rsync`, and found that the former appears not to be working on NetBSD. To try to validate this, here's output of `/sbin/mount` within freebsd-vm, where the job succeeds:

```
/dev/gpt/rootfs on / (ufs, local, soft-updates)
devfs on /dev (devfs)
/dev/gpt/efiesp on /boot/efi (msdosfs, local)
host:work on /home/runner/work (fusefs.sshfs)
```

And within netbsd-vm, where the job gives errors such as `fatal: could not create work tree dir: No such file or directory`:

```
/dev/dk0 on / type ffs (local)
tmpfs on /tmp type tmpfs (local)
kernfs on /kern type kernfs (local)
ptyfs on /dev/pts type ptyfs (local)
procfs on /proc type procfs (local)
tmpfs on /var/shm type tmpfs (local)
```

I'm happy to try something further to validate the problem and/or test a fix.

**Comment by Neilpang** [comment]
Here is the test: https://github.com/vmactions/netbsd-vm/actions/runs/7675558306/job/20921929690

It seems sshfs is working here.

**Comment by Neilpang** [comment]
sorry,  it seems not working.  give me some time to check more.

**Comment by Neilpang** [comment]
fixed, try with the latest release version

**Comment by schmonz** [comment]
I now see `/dev/puffs on /home/runner/work type puffs|host:work (nodev, nosuid)` mounted. Something's still not quite right, though. If I throw a `pwd` right after the `/sbin/mount`, it gives this error: `pwd: getcwd() failed: No such file or directory`. For comparison, openbsd-vm says `/home/runner/work/pkgsrc-mlog/pkgsrc-mlog`, which makes sense given that the shell connection is made with `exec ssh: cd $GITHUB_WORKSPACE;`. Not sure why NetBSD's doesn't give the same result. This is with `usesh: true`, in case that affects the outcome.

**Comment by Neilpang** [comment]
weird

**Comment by Neilpang** [comment]
it's like a random issue.

**Comment by hebasto** [comment]
> it's like a random issue.

However, the "Test custom shell" steps in all "sshfs ..." CI jobs have error message:
```
pwd: getcwd() failed: No such file or directory
```

**Comment by Neilpang** [comment]
@hebasto 
please try with the latest release,   it supports `nfs` now.
you can use it.

**Comment by hebasto** [comment]
> please try with the latest release, it supports `nfs` now.
> you can use it.

Thanks! It seems to be working.

**Comment by larseggert** [comment]
`sshfs` seems still broken: https://github.com/mozilla/mtu/actions/runs/13672005643/job/38224099535?pr=99#step:6:2185
